name: XpStorage
main: com.lith.xpstorage.Plugin

version: 0.0.2
api-version: 1.20

description: A MineCraft plugin that allows users to use stored xp to fix mending items
author: Lith
website: https://github.com/ImLith/MC-XpStorage

depend: [LithCore]
softdepend: []
